MODELS = autotrans f16

default:
	for model in $(MODELS) ; do $(MAKE) -C $$model default ; done
all:
	for model in $(MODELS) ; do $(MAKE) -C $$model all ; done
cleanall:
	for model in $(MODELS) ; do $(MAKE) -C $$model cleanall ; done
realclean:
	for model in $(MODELS) ; do $(MAKE) -C $$model realclean ; done
clean:
	for model in $(MODELS) ; do $(MAKE) -C $$model clean ; done
